### ISSUE TITLE
add "maintenance windows" for expiring nodes

### ISSUE THREAD

**Issue by camaeel** [aws/karpenter-provider-aws#6320] opened 2024-06-05 07:05 UTC
### Description

**What problem are you trying to solve?**
If I have some statefull applications running in my cluster, which can be disrupted only on some specific times of the day I can't use nodePools .distruption.expireAfter setting. I have to expire those nodes on my own. 

If I could define a disruption window for such a node pool, Karpenter could wait with expiring (or maybe even consolidating) those nodes until next such a window. 

**How important is this feature to you?**
Without this I need to implement my own solution with external tooling, and I can't easily start new nodes before expiring old ones.

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by njtran** [comment] 2024-06-10 20:45
Can you add your use-cases here: https://github.com/kubernetes-sigs/karpenter/pull/1303?

Currently, Karpenter already has a concept of [Node Disruption Budgets](https://karpenter.sh/docs/concepts/disruption/#disruption-budgets), where we're adding the functionality to have a per-reason budget here: https://github.com/kubernetes-sigs/karpenter/pull/991

We're thinking of making Expiration forceful, which means that you wouldn't be able to block Expiration by NodePool Disruption Budgets. Your feedback on https://github.com/kubernetes-sigs/karpenter/pull/1303 would be very useful! In the meantime, I'm going to close this as a duplicate of https://github.com/kubernetes-sigs/karpenter/issues/924 which has been closed, since the RFC has been closed.

**Closed by njtran** 2024-06-10 20:45 UTC
Labels: feature, needs-triage

**Comment by camaeel** [comment] 2024-06-11 06:37
@njtran Thank you for pointing me to Disruption Budgets. This should do the trick. 
Forceful expiration that would omit "maintenance window" defined with Disruption Budgets would be not acceptable by the business owners.
