### ISSUE TITLE
Support placement group feature.

### ISSUE THREAD

**Issue by gaussye** [aws/karpenter-provider-aws#5479] opened 2024-01-16 06:10 UTC
### Description

**What problem are you trying to solve?**
If I created a placement group, can karpenter attach the placment group to it? So far i can not find any configurations for that.
**How important is this feature to you?**

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by baznikin** [comment] 2024-01-16 15:35
Worked around by
```
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: default
spec:
  userData: |
      #!/bin/bash
      echo "$(jq .runtimeRequestTimeout=\"7m\" /etc/kubernetes/kubelet/kubelet-config.json)" > /etc/kubernetes/kubelet/kubelet-config.json
```

**Comment by jmdeal** [comment] 2024-01-16 17:32
Closing as a duplicate of https://github.com/aws/karpenter-provider-aws/issues/3324. I'd make sure to check out the Placement Group design PR and leave any feedback you might have: https://github.com/aws/karpenter-provider-aws/pull/5389. One of the open questions there is whether we should support using existing placement groups or only create new ones, it sounds like you have a use case for the former so your feedback would definitely be appreciated.

**Closed by jmdeal** 2024-01-16 17:32 UTC
Labels: feature, needs-triage
