### ISSUE TITLE
Getting Started with Karpenter

### ISSUE THREAD

**Issue by davivcgarcia** [aws/karpenter-provider-aws#6445] opened 2024-07-02 11:25 UTC
Most of the documentation refers to Karpenter as something exclusively available for Amazon EKS, but this is not true. Karpenter could be provisioned in any Kubernetes cluster running on AWS or Azure.

```
To use Karpenter, you must be running a supported Kubernetes cluster on a supported cloud provider. Currently, only EKS on AWS is supported.
```

**Comment by mausch** [comment] 2024-07-11 10:32
duplicate of https://github.com/aws/karpenter-provider-aws/issues/6465 ?

**Closed** 2024-07-11 10:54 UTC
