### ISSUE TITLE
Upgrading to chart v0.31.4 uses image tag v0.30.0

### ISSUE THREAD

**Issue by ravitst** [aws/karpenter-provider-aws#5848] opened 2024-03-13 12:57 UTC
### Description

**Observed Behavior**:
We are planning an upgrade from 0.31.4 to 0.32.7.
Following the guide for v1beta1 Migration we need to check that after upgrading to v0.31.4 the image tag is v0.31.0:

![image](https://github.com/aws/karpenter-provider-aws/assets/110096213/9769a141-2f89-4964-a21d-ad95c7f96679)
But, looking at v0.31.4 chart I see that the chart version in Chart.yaml is v0.30.0 and the image tag in values.yaml is v0.30.0:
https://github.com/aws/karpenter-provider-aws/blob/release-v0.31.x/charts/karpenter/values.yaml
https://github.com/aws/karpenter-provider-aws/blob/release-v0.31.x/charts/karpenter/Chart.yaml

I couldn't find a release with image tag v0.31.0.

**Expected Behavior**:
After upgrading to v0.31.4 the image tag should be v0.31.0 as described in v1beta1 Migration manual.

**Reproduction Steps** (Please include YAML):
Upgrading to v0.31.4

**Versions**:
- Chart Version: v0.31.4
- Kubernetes Version (`kubectl version`): v1.27.9

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

**Comment by jonathan-innis** [comment] 2024-03-15 00:58
This is a duplicate of #5415. We definitely need to improve this in our repo and would happily take a contribution that improved this in our release automation. For now, the recommendation is to rely on the chart that is pushed with the right tag in our OCI repo: `oci://public.ecr.aws/karpenter/karpenter`

**Closed by jonathan-innis** 2024-03-15 00:58 UTC
Labels: bug, needs-triage
