### ISSUE TITLE
Launch Template Removal After Uninstalling Karpenter

### ISSUE THREAD

**Issue by eminalemdar** [aws/karpenter-provider-aws#995] opened 2021-12-14 23:42 UTC
## Version

**Karpenter**: v0.5.2

**Kubernetes**: v1.21

## Expected Behavior
After uninstalling Karpenter from the cluster or completely deleting the cluster, cleanup process should remove all resources related to Karpenter including Launch Templates those are created for Provisioners.

## Actual Behavior
After removing Karpenter from the cluster there are some orphaned Launch Templates left in the AWS account that everyone should manually perform the cleanup...

## Steps to Reproduce the Problem
- Install Karpenter,
- Add some Provisioner CRDs,
- Deploy some sample applications and let Karpenter provision new nodes using Launch Templates,
- Remove the applications,
- Remove Karpenter provisioner CRDs,
- Uninstall Karpenter,
- Delete the Kubernetes cluster,
- Check EC2 Launch Templates.

**Comment by mikesir87** [comment] 2021-12-17 01:53
I agree with this, but curious if you have any ideas how to pull this off. I don't think you want to simply do it when the pod is being removed, as that will cause all upgrades to nuke all of the launch templates (maybe that's a good thing to do anyways???). I guess a finalizer on the pod could work to let it have some tear down activities?

I might be willing to pick this one up next if we figure out _how_ this should be pulled off.

**Comment by eminalemdar** [comment] 2021-12-17 06:39
> I agree with this, but curious if you have any ideas how to pull this off. I don't think you want to simply do it when the pod is being removed, as that will cause all upgrades to nuke all of the launch templates (maybe that's a good thing to do anyways???). I guess a finalizer on the pod could work to let it have some tear down activities?
> 
> I might be willing to pick this one up next if we figure out _how_ this should be pulled off.

I didn't mean Karpenter should remove the Launch Templates after a pod removal. Because like you said removing a LT after every pod removal would cause a lot of unnecessary event. Karpenter should remove the LTs after Karpenter itself is removed from the cluster and after the cluster deletion. There should be a usual Cleanup procedure for every resource created by Karpenter.

**Comment by vicyap** [comment] 2022-01-08 05:06
Is this a dupe of #444 ?

**Comment by eminalemdar** [comment] 2022-04-26 10:29
> Is this a dupe of #444 ?

I believe so. If Karpenter now has a proper Cleanup process for LTs, then this issue can be closed.

**Comment by tzneal** [comment] 2022-04-26 12:38
Karpenter periodically cleans up old launch templates, but it doesn't delete them all upon an uninstall. I think that is what this issue is referring to.

**Comment by jonathan-innis** [comment] 2022-08-25 21:03
Have we though about using a `pre-delete` helm hook to achieve this?

**Comment by bwagner5** [comment] 2022-08-26 16:10
> Have we though about using a `pre-delete` helm hook to achieve this?

A pre-delete hook may not have the required permissions to delete launch templates and it would only solve for Helm. I think on shutdown would be better.

**Comment by sadath-12** [comment] 2023-10-12 08:52
Assign me this @jonathan-innis . I'll see what I can come up with

**Comment by jigisha620** [comment] 2024-01-06 00:12
Can you please assign this to me? @jonathan-innis Thanks!

**Closed** 2024-01-23 20:37 UTC
Labels: feature, v1
