### ISSUE TITLE
The bitnami/kubectl image at public.ecr.aws is only having amd64 architecture

### ISSUE THREAD

**Issue by marcofranssen** [aws/karpenter-provider-aws#6819] opened 2024-08-21 08:38 UTC
### Description

**Observed Behavior**:

The bitnami/kubectl image (used in the postInstallHook) at public.ecr.aws is only having amd64 architecture.

**Expected Behavior**:

The bitnami/kubectl image (used in the postInstallHook) at public.ecr.aws is having the multi architecture like the image on dockerhub.

**Reproduction Steps** (Please include YAML):

```
$ crane manifest public.ecr.aws/bitnami/kubectl:1.30
{"schemaVersion":2,"mediaType":"application/vnd.docker.distribution.manifest.list.v2+json","manifests":[{"mediaType":"application/vnd.docker.distribution.manifest.v2+json","digest":"sha256:68a21ff34c2a67329faa4d6088272d54d4a4e7a21076b3a435624e45503a17ab","size":430,"platform":{"architecture":"amd64","os":"linux"}}]}
$ crane manifest bitnami/kubectl:1.30
{"schemaVersion":2,"mediaType":"application/vnd.docker.distribution.manifest.list.v2+json","manifests":[{"mediaType":"application/vnd.docker.distribution.manifest.v2+json","size":430,"digest":"sha256:68a21ff34c2a67329faa4d6088272d54d4a4e7a21076b3a435624e45503a17ab","platform":{"architecture":"amd64","os":"linux"}},{"mediaType":"application/vnd.docker.distribution.manifest.v2+json","size":430,"digest":"sha256:75243f00f9d7313cbf0142258edab749f9b4461f8efbbe970df1193c7aef35a0","platform":{"architecture":"arm64","os":"linux"}}]}
```

**Versions**:
- Chart Version: v1.0.0
- Kubernetes Version (`kubectl version`): 1.30

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
The bitnami/kubectl image at public.ecr.aws is only having amd64 architecture

**Comment by jmdeal** [comment] 2024-08-21 18:45
Closing as a duplicate of #6775

**Closed by jmdeal** 2024-08-21 18:45 UTC
Labels: bug, needs-triage
