### ISSUE TITLE
Release Version doesn't match Helm Chart and Image Version

### ISSUE THREAD

**Issue by michaelswierszcz** [aws/karpenter-provider-aws#7547] opened 2024-12-20 17:06 UTC
### Description

**Observed Behavior**:

Go to releases page, download Release 0.37.8. Navigate to the chart and notice the chart version is 0.36.0 and the image is 0.36.0

**Expected Behavior**:

Release Version matches chart version or at least the image version

**Reproduction Steps** (Please include YAML):

Go to releases page, download Release 0.37.8. Navigate to the chart and notice the chart version is 0.36.0 and the image is 0.36.0

**Versions**:
- Chart Version: 0.37.6 but i see it in 1.1.0 as well
- Kubernetes Version (`kubectl version`):

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jmdeal** [comment] 2024-12-20 22:45
Closing as a duplicate of https://github.com/aws/karpenter-provider-aws/issues/5415.

**Closed by jmdeal** 2024-12-20 22:45 UTC
Labels: bug, needs-triage
