### ISSUE TITLE
[Administrative-issue] Git tag does not match Chart.yaml version

### ISSUE THREAD

**Issue by pydolan** [aws/karpenter-provider-aws#6846] opened 2024-08-22 16:53 UTC
### Description

**Observed Behavior**:
In the last few releases, I've noticed the version in the Chart.yaml does match the git tag:
- https://github.com/aws/karpenter-provider-aws/blob/v1.0.0/charts/karpenter/Chart.yaml ("v0.37.0" in yaml)
- https://github.com/aws/karpenter-provider-aws/blob/v0.37.0/charts/karpenter/Chart.yaml ("v0.36.0" in yaml) 

This causes a mismatch when installing the helm chart directly from Git.

The release branch (`release-v1.0.x`) currently has this issue as well (as of Aug 22 2024)

**Expected Behavior**:
Version in Chart.yaml should match Github tag

**Reproduction Steps** (Please include YAML):
N/A

**Versions**:
- Chart Version: v1.0.0
- Kubernetes Version (`kubectl version`): N/A

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by pydolan** [comment] 2024-08-22 17:20
I should also note: I first discovered this via seeing `karpenter version is not compatible with K8s version 1.30` in my logs when running the v0.37.0 tag from GH. 

Initially I assumed this was a harmless error, but because the Helm Chart uses the `appVersion` for the controller image ([here](https://github.com/aws/karpenter-provider-aws/blob/main/charts/karpenter/templates/_helpers.tpl#L68)), this causes the wrong version to be deployed.

**Comment by jmdeal** [comment] 2024-08-22 17:53
Closing as a duplicate of #5415

**Closed by jmdeal** 2024-08-22 17:53 UTC
Labels: bug, needs-triage
