### ISSUE TITLE
Unable to launch vt1 with amd.com/ama_u30 limit on pod

### ISSUE THREAD

**Issue by dcarrion87** [aws/karpenter-provider-aws#5403] opened 2023-12-29 08:45 UTC
### Description

**Observed Behavior**:

When launching pod with limit amd.com/ama_u30 = 1 and constraining to vt1.3xlarge 

> {"level":"ERROR","time":"2023-12-29T08:13:48.025Z","logger":"controller.provisioner","message":"Could not schedule pod, incompatible with nodepool \"stream\", daemonset overhead={\"cpu\":\"150m\",\"pods\":\"3\"}, no instance type satisfied resources {\"amd.com/ama_u30\":\"1\",\"cpu\":\"150m\",\"pods\":\"4\"} and requirements karpenter.sh/nodepool In [stream], node.kubernetes.io/instance-type In [vt1.3xlarge] (no instance type has enough resources)","commit":"1072d3b","pod":"default/stream-stream1-5f4dd5745c-2gv2s"}

Removing the `amd.com/ama_u30` limit allows pod to launch but device plugin never mounts devices.

**Expected Behavior**:

Ability for Karpenter to recognise amd.com/ama_u30 for vt1 instances or just ignore it for launching purposes.

**Reproduction Steps** (Please include YAML):

Create node pool. E.g.:

```
    apiVersion: karpenter.sh/v1beta1
    kind: NodePool
    metadata:
      name: stream
    spec:
      template:
        spec:
          nodeClassRef:
            name: stream
          taints:
            - key: stream
              effect: NoSchedule
          requirements:
            - key: "node.kubernetes.io/instance-type"
              operator: In
              values: ["vt1.3xlarge"]
      limits:
        cpu: 9999
      disruption:
        consolidationPolicy: WhenEmpty
        consolidateAfter: "3600s"
```

Try assign a pod with `amd.com/ama_u3` and vt1.3xlarge requirement. E.g.:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      hostNetwork: true
      hostPID: true
      terminationGracePeriodSeconds: 0
      containers:
      - name: test
        image: ubuntu:22.04
        command: ["/bin/sh", "-c", "while true; do sleep 1; done"]
        resources:
          limits:
            amd.com/ama_u30: 1
      tolerations:
      - key: "stream"
        effect: "NoSchedule"
      nodeSelector:
        "node.kubernetes.io/instance-type": "vt1.3xlarge"
```

**Versions**:
- Chart Version: 0.32
- Kubernetes Version (`kubectl version`): 1.28

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jmdeal** [comment] 2023-12-29 17:20
Karpenter isn't natively aware of this resource, that's why Karpenter can't launch an instance if the resource requirement is specified on the pod since it is not aware of any instances which fulfill those requirements. I'm not sure if this needs to be a requirement for your use case, with taints on the nodes and tolerations on the pods you can ensure that only these pods schedule to these specialized nodes.

As for the device drivers, while I don't have personal experience with the Xilinx device plugin it looks like it is deployed via a daemonset. Are you able to confirm if the daemonset is being scheduled on the node? Are there any additional drivers you may need to install that aren't included in the AMI?

**Comment by dcarrion87** [comment] 2023-12-30 00:05
@jmdeal thanks for your response. The taints and tolerations work well. Unfortunately without the resource limit specified the devices are never mounted. And with the resource limits specified Karpenter never provisions the node. I've had to get around this by privileging the pod so the devices are mounted in that way. Not an ideal solution.

**Comment by jonathan-innis** [comment] 2024-01-02 19:39
> I'd rather Karpenter just ignore that specific limit and allow the node to provision based on the instance type and other limits

There's a relevant mega-issue around supporting extended resources here https://github.com/kubernetes-sigs/karpenter/issues/751. This looks like a duplicate of that issue. It would be good to add your use-case over there. Going to close this one as a duplicate for now.

**Closed by jonathan-innis** 2024-01-02 19:39 UTC
Labels: question
