### ISSUE TITLE
What is the best way to upgrade EKS versions when pinning AMIs?

### ISSUE THREAD

**Issue by mrparkers** [aws/karpenter-provider-aws#6050] opened 2024-04-17 18:59 UTC
### Description

**Context**:
In the past, our Karpenter configuration utilized `EC2NodeClass` objects that set `.spec.amiFamily` to `AL2`, which allowed Karpenter to automatically select the latest appropriate AMI for our Kubernetes nodes.  Since we're currently on EKS 1.27, this would select `amazon-eks-gpu-node-1.27-v20240409` for GPU nodes, `amazon-eks-arm64-node-1.27-v20240409` for ARM nodes, and `amazon-eks-node-1.27-v20240409` for everything else.

However, recently the EKS team published a bad AMI that was affected by a bug that caused GPU nodes to not start correctly (https://github.com/awslabs/amazon-eks-ami/issues/1744).  Karpenter automatically upgraded all of our clusters to use this AMI, causing a production outage for GPU workloads.  So we have decided that this behavior of automatically upgrading AMIs is no longer acceptable for a production environment.

Now, we have a specific `EC2NodeClass` that is referenced by a `NodePool` that provisions GPU nodes within the `g4` and `g5` instance families.  It looks something like this:

```yaml
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: gpu-pinned-ami
spec:
  amiSelectorTerms:
    - name: "amazon-eks-gpu-node-1.27-v20240315"
  instanceStorePolicy: RAID0
  role: staging-node-instance-role
  securityGroupSelectorTerms:
  - tags:
      karpenter.sh/discovery: staging
  subnetSelectorTerms:
  - tags:
      karpenter.sh/discovery: staging
  tags:
    datadog: monitored
    karpenter.sh/discovery: staging
```

This works for now, but we are starting to upgrade to EKS 1.28, and we don't understand how to correctly do this when we're pinning AMI versions.

**Observed Behavior**:
We have tried two different configurations, both of which behaved differently than I expected.

First, we tried using a wildcard to represent the EKS version:

```yaml
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: gpu-pinned-ami
spec:
  amiSelectorTerms:
    - name: "amazon-eks-gpu-node-*-v20240315"
  instanceStorePolicy: RAID0
  role: staging-node-instance-role
  securityGroupSelectorTerms:
  - tags:
      karpenter.sh/discovery: staging
  subnetSelectorTerms:
  - tags:
      karpenter.sh/discovery: staging
  tags:
    datadog: monitored
    karpenter.sh/discovery: staging
```

I expected Karpenter to understand that its running within a 1.27 cluster, and thus to prefer AMIs that use that version.  The idea here being that, after upgrading to 1.28, Karpenter would see this and start selecting the 1.28 AMIs instead.  However, this configuration resulted in nodes using a 1.26 AMI within a 1.27 cluster.

In the second attempt, we tried to explicitly list the two acceptable AMIs:

```yaml
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: gpu-pinned-ami
spec:
  amiSelectorTerms:
    - name: "amazon-eks-gpu-node-1.27-v20240315"
    - name: "amazon-eks-gpu-node-1.28-v20240315"
  instanceStorePolicy: RAID0
  role: staging-node-instance-role
  securityGroupSelectorTerms:
  - tags:
      karpenter.sh/discovery: staging
  subnetSelectorTerms:
  - tags:
      karpenter.sh/discovery: staging
  tags:
    datadog: monitored
    karpenter.sh/discovery: staging
```

In this case, I expected Karpenter again to understand that it is currently running within a 1.27 cluster, and to select the 1.27 AMI, then switch to the 1.28 AMI after the EKS control plane upgrade is complete.  But in this case, Karpented selected a 1.28 AMI even though we were running a 1.27 cluster.

**Expected Behavior**:
In both cases, Karpenter seems to prefer selecting AMIs that are using Kubernetes versions that are different than the version we're actually running.  It's possible that this is truly random and I'm just getting unlucky with this configuration, but I expected a little bit more intelligence here when the `amiSelectorTerms` results in multiple matches.

**Reproduction Steps** (Please include YAML): See the observed behavior section

**Questions**:
How are users expected to perform an EKS upgrade when they're pinning AMI versions?  Should we be creating multiple `EC2NodeClass` objects, and thus duplicate this configuration plus the configuration of every `NodePool` that references it?

Are there some controls that I'm missing here?

Could we perhaps have some sort of variable that we could use within `amiSelectorTerms` that can be substituted for the EKS version at runtime?

**Versions**:
- Chart Version: 0.36.0
- Kubernetes Version (`kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.4", GitCommit:"fa3d7990104d7c1f16943a67f11b154b71f6a132", GitTreeState:"clean", BuildDate:"2023-07-19T12:14:48Z", GoVersion:"go1.20.6", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"27+", GitVersion:"v1.27.11-eks-b9c9ed7", GitCommit:"f19f83c16ca534237fbfb65bc580d51752b98c91", GitTreeState:"clean", BuildDate:"2024-03-02T03:46:53Z", GoVersion:"go1.21.7", Compiler:"gc", Platform:"linux/amd64"}
```

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jonathan-innis** [comment] 2024-04-18 05:47
I think the biggest problem for us here is: How do we know the Kubernetes version that the AMI is running without actually upgrading nodes to it? Despite the fact that the Kubernetes version is in the name of the AMI that you are selecting on, there's no semantic today that would tell us that this part of the name is denoting the Kubernetes version. Realistically, it seems we have a few options to attack this (one of which is already open as another feature request):
1. Always attempt to parse the AMI name for a kubernetes version "looking" think. If we find some Semver in the name, treat this as the K8s version and only match AMIs that match our current K8s version (a little unintuitive, probably not ideal)
2. Allow users to set the K8s version through a well-known tag. Something like `k8s-version: 1.28`. We treat this tag as "special". This tag is part of the "metadata" of the image, we will always attempt to match this tag if we find multiple AMIs and one of them has a matching element to the current K8s version, we'll use that one.
3. Allow users to set template parameters in the AMISelectorTerms that are injected by Karpenter. You could do an `amiSelectorTerms` block like below. This would let you effectively use this Karpenter-injected value in the name or in a tag value, really whatever you wanted and just leverage the discovered server version.
```
amiSelectorTerms:
  - tags:
        k8s-version: {{ .k8sVersion }}
```

Personally, my preference is number 3 -- this gives the most flexibility -- and this is what is recomended in another linked issue here: https://github.com/aws/karpenter-provider-aws/issues/1495#issuecomment-1825239102

**Comment by jonathan-innis** [comment] 2024-04-18 05:57
If number 3 also sounds reasonable to you, I'd like to just consolidate these requests together and close this one as a duplicate of #1495. We can discuss more over there so that we keep all of the conversation together.

**Comment by mrparkers** [comment] 2024-04-18 15:24
I agree, number 3 sounds best to me as well.  If you want to close this as a duplicate of #1495 that's perfectly fine with me.

For now, we will probably just upgrade the control plane first, then update our `EC2NodeClass` definitions to point to the v1.28 version of the AMIs we need.

Thanks for the quick response!

**Comment by jonathan-innis** [comment] 2024-04-21 23:50
Closing as a duplicate of #1495. 100% agree that we should support templating the kubernetes version into the amiSelectorTerms to make this kind of scenario easier for users with the non-default AMIs. If this was something you were interested in opening a PR for, I'd be all for it 🚀

**Closed by jonathan-innis** 2024-04-21 23:50 UTC
Labels: feature

**Comment by peterreji** [comment] 2024-05-06 12:55
I'm also in a similar situation, running EKS version 1.26 with karpenter AMI pinned to amazon-eks-node-1.26-v20240117. 

so what's the right approach to follow? shall I upgrade the EKS cluster first to 1.27 and then update the amiSelector with the AMI for EKS 1.27?

**Comment by adityamandke23** [comment] 2025-04-02 04:35
@peterreji facing a similar situation for upgrade from v1.29 to v1.30, what did you do?

**Comment by peterreji** [comment] 2025-04-02 07:19
> [@peterreji](https://github.com/peterreji) facing a similar situation for upgrade from v1.29 to v1.30, what did you do?

@adityamandke23 I first upgraded my EKS cluster to 1.27 and then updated Karpenter amiSelector to 1.27. because the kubelet can be 3 versions behind the cluster version - https://kubernetes.io/releases/version-skew-policy/#kubelet

You can do the same for v1.29 to v1.30.
