### ISSUE TITLE
Surface AMI family as label

### ISSUE THREAD

**Issue by ryanfaircloth** [aws/karpenter-provider-aws#5482] opened 2024-01-16 22:56 UTC
### Description

I have a corner use case with topolvm where the component must execute a command on the host via nsenter that command isn't available in bottlerocket or AL2 but is in ubuntu so for this workload I need to set nodeaffinity to pick a nodepool based on a nodeclass using ubuntu could we surface that as an label. 

**How important is this feature to you?**

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jmdeal** [comment] 2024-01-16 23:48
Going to close as a duplicate of #5449 and #3074.

**Closed by jmdeal** 2024-01-16 23:48 UTC
Labels: feature, needs-triage
