### ISSUE TITLE
On-Demand/Spot Ratio Split not working as expected

### ISSUE THREAD

**Issue by clarifai-fmarceau** [aws/karpenter-provider-aws#5489] opened 2024-01-18 19:33 UTC
### Description

**Observed Behavior**:
Capacity-spread configured on NodePools is not respected when using topologySpreadConstraints on some deployment/ statefulset.

**Expected Behavior**:
I expect the ratio that comes from the capacity-spread requirement on two NodePools to be respected as it is mentioned in the documentation :
- https://karpenter.sh/preview/concepts/scheduling/#on-demandspot-ratio-split

**Reproduction Steps** (Please include YAML):
Create these two NodePools :
```
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: memcached
spec:
  disruption:
    consolidateAfter: 30s
    consolidationPolicy: WhenEmpty
    expireAfter: 720h
  limits:
    cpu: "60"
    memory: 150Gi
  template:
    metadata: {}
    spec:
      nodeClassRef:
        name: default
      requirements:
      - key: node.kubernetes.io/instance-type
        operator: In
        values:
        - c6in.large
        - c6in.xlarge
        - c6in.2xlarge
      - key: karpenter.sh/capacity-type
        operator: In
        values:
        - on-demand
      - key: kubernetes.io/os
        operator: In
        values:
        - linux
      - key: kubernetes.io/arch
        operator: In
        values:
        - amd64
      - key: capacity-spread
        operator: In
        values:
        - "1"
        - "2"
      taints:
      - effect: NoSchedule
        key: service
        value: memcached
status:
  resources:
    cpu: "24"
    ephemeral-storage: 125755272Ki
    memory: 47889176Ki
    pods: "348"
---
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: memcached-spot
spec:
  disruption:
    consolidateAfter: 30s
    consolidationPolicy: WhenEmpty
    expireAfter: 720h
  limits:
    cpu: "60"
    memory: 150Gi
  template:
    metadata: {}
    spec:
      nodeClassRef:
        name: default
      requirements:
      - key: node.kubernetes.io/instance-type
        operator: In
        values:
        - c6in.large
        - c6in.xlarge
        - c6in.2xlarge
      - key: karpenter.sh/capacity-type
        operator: In
        values:
        - spot
      - key: kubernetes.io/os
        operator: In
        values:
        - linux
      - key: kubernetes.io/arch
        operator: In
        values:
        - amd64
      - key: capacity-spread
        operator: In
        values:
        - "3"
      taints:
      - effect: NoSchedule
        key: service
        value: memcached
status: {}
```
Add to some Statefulset/ Deployment the following :
```
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: karpenter.sh/nodepool
                operator: In
                values:
                - memcached
                - memcached-spot
...
      tolerations:
      - effect: NoSchedule
        key: service
        operator: Equal
        value: memcached

...
      topologySpreadConstraints:
      - labelSelector:
          matchLabels:
            app.kubernetes.io/name: memcached
        maxSkew: 1
        topologyKey: capacity-spread
        whenUnsatisfiable: DoNotSchedule

```
Note: I tried without the "labelSelector" and got the same behavior.

**Versions**:
- Chart Version: v0.33.0
- Kubernetes Version (`kubectl version`): v1.27.7-eks-e71965b

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jmdeal** [comment] 2024-01-18 23:40
I'm unable to reproduce the issue you described in the Karpenter slack with the nodepools provided. The NodePools were used verbatim, I used the following deployment to test:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inflate
spec:
  replicas: 9
  selector:
    matchLabels:
      app: inflate
  template:
    metadata:
      labels:
        app: inflate
    spec:
      tolerations:
        - effect: NoSchedule
          key: service
          operator: Equal
          value: memcached
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: karpenter.sh/nodepool
                  operator: In
                  values:
                    - memcached
                    - memcached-spot
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: capacity-spread
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: inflate
      terminationGracePeriodSeconds: 0
      containers:
        - name: inflate
          image: public.ecr.aws/eks-distro/kubernetes/pause:3.7
          resources:
            requests:
              cpu: 100m
```
This resulted in 3 nodes, two on-demand and one spot as expected. Are you able to provide any logs to better help diagnose here?

**Comment by jmdeal** [comment] 2024-01-18 23:41
Also could you update the issue description with some more of the details you gave in the Karpenter slack about how the spread wasn't being respected?

**Comment by clarifai-fmarceau** [comment] 2024-01-19 13:48
I did that test late yesterday but again this morning I've set back the replicas of the sts to 3 and got the following capacity spread distribution :
```
NAME                           STATUS   ROLES    AGE     VERSION               INTERNAL-IP    EXTERNAL-IP   OS-IMAGE         KERNEL-VERSION                  CONTAINER-RUNTIME    INSTANCE-TYPE   ZONE         CAPACITY-TYPE   NODEPOOL           CAPACITY-SPREAD
ip-10-0-73-143.ec2.internal    Ready    <none>   4m9s    v1.27.7-eks-e71965b   10.0.73.143    <none>        Amazon Linux 2   5.10.199-190.747.amzn2.x86_64   containerd://1.7.2   c6in.xlarge     us-east-1b   on-demand       memcached          1
ip-10-0-149-245.ec2.internal   Ready    <none>   4m8s    v1.27.7-eks-e71965b   10.0.149.245   <none>        Amazon Linux 2   5.10.199-190.747.amzn2.x86_64   containerd://1.7.2   c6in.xlarge     us-east-1c   spot            memcached-spot     3
ip-10-0-14-201.ec2.internal    Ready    <none>   4m7s    v1.27.7-eks-e71965b   10.0.14.201    <none>        Amazon Linux 2   5.10.199-190.747.amzn2.x86_64   containerd://1.7.2   c6in.xlarge     us-east-1a   on-demand       memcached          1
```

**Comment by jmdeal** [comment] 2024-01-22 20:46
I've been unable to replicate with the provided resources, are there any other pods in the cluster that could match the label selector? Artificially preventing the statefulset from scheduling against all domains results in a provisioner error in v0.33 for me:
```
karpenter-5c88f85c48-2jc9x controller {"level":"ERROR","time":"2024-01-22T20:44:32.004Z","logger":"controller.provisioner","message":"Could not schedule pod, incompatible with nodepool \"memcached\", daemonset overhead={\"cpu\":\"150m\",\"pods\":\"2\"}, unsatisfiable topology constraint for topology spread, key=capacity-spread (counts = map[1:1 2:1 3:0], podDomains = capacity-spread Exists, nodeDomains = capacity-spread In [1 2]); incompatible with nodepool \"memcached-spot\", daemonset overhead={\"cpu\":\"150m\",\"pods\":\"2\"}, incompatible requirements, key karpenter.sh/nodepool, karpenter.sh/nodepool In [memcached] not in karpenter.sh/nodepool In [memcached-spot]","commit":"2dd7fdc","pod":"default/memcached-1"}
```
I'm wondering if there are any other pods in the cluster which match the label selector and are affecting the topology spread calculation.

**Comment by clarifai-fmarceau** [comment] 2024-01-24 13:53
So I did another test just to be 110% sure that there's no conflict with the app name, I updated the label to the following on the statefulset :
> app.kubernetes.io/name: "jmdeal"

I deployed the statefulset, Karpenter got the topologySpreadConstraints at first. Then I scaled it back to 0 replicas, waited for the nodes to be removed from the cluster. Following that, I scaled back the STS to 3 replicas and ended up again with this :
```
ip-10-0-148-191.ec2.internal   NotReady   <none>   2s      v1.27.7-eks-e71965b   10.0.148.191   <none>        Amazon Linux 2   5.10.199-190.747.amzn2.x86_64   containerd://1.7.2   c6in.xlarge     us-east-1c   spot            memcached-spot     3
ip-10-0-124-114.ec2.internal   NotReady   <none>   2s      v1.27.7-eks-e71965b   10.0.124.114   <none>        Amazon Linux 2   5.10.199-190.747.amzn2.x86_64   containerd://1.7.2   c6in.xlarge     us-east-1b   spot            memcached-spot     3
ip-10-0-37-251.ec2.internal    NotReady   <none>   1s      v1.27.7-eks-e71965b   10.0.37.251    <none>        Amazon Linux 2   5.10.199-190.747.amzn2.x86_64   containerd://1.7.2   c6in.xlarge     us-east-1a   spot            memcached-spot     3
```

**Comment by clarifai-fmarceau** [comment] 2024-01-24 15:47
Ran another test with the new label, ended up with these nodes :
```
ip-10-0-171-164.ec2.internal   Ready    <none>   103s    v1.27.7-eks-e71965b   10.0.171.164   <none>        Amazon Linux 2   5.10.199-190.747.amzn2.x86_64   containerd://1.7.2   c6in.xlarge     us-east-1c   on-demand       memcached          1
ip-10-0-57-20.ec2.internal     Ready    <none>   101s    v1.27.7-eks-e71965b   10.0.57.20     <none>        Amazon Linux 2   5.10.199-190.747.amzn2.x86_64   containerd://1.7.2   c6in.xlarge     us-east-1a   on-demand       memcached          2
ip-10-0-112-48.ec2.internal    Ready    <none>   94s     v1.27.7-eks-e71965b   10.0.112.48    <none>        Amazon Linux 2   5.10.199-190.747.amzn2.x86_64   containerd://1.7.2   c6in.xlarge     us-east-1b   on-demand       memcached          1
```

Here are the Karpenter logs :
```
{"level":"INFO","time":"2024-01-24T15:43:21.112Z","logger":"controller.provisioner","message":"found provisionable pod(s)","commit":"2dd7fdc","pods":"default/memcached-0, default/memcached-2, default/memcached-1","duration":"51.339303ms"}
{"level":"INFO","time":"2024-01-24T15:43:21.113Z","logger":"controller.provisioner","message":"computed new nodeclaim(s) to fit pod(s)","commit":"2dd7fdc","nodeclaims":3,"pods":3}
{"level":"INFO","time":"2024-01-24T15:43:21.131Z","logger":"controller.provisioner","message":"created nodeclaim","commit":"2dd7fdc","nodepool":"memcached","nodeclaim":"memcached-hxtbj","requests":{"cpu":"2155m","memory":"4216Mi","pods":"6"},"instance-types":"c6in.2xlarge, c6in.xlarge"}
{"level":"INFO","time":"2024-01-24T15:43:21.139Z","logger":"controller.provisioner","message":"created nodeclaim","commit":"2dd7fdc","nodepool":"memcached","nodeclaim":"memcached-sdk7g","requests":{"cpu":"2155m","memory":"4216Mi","pods":"6"},"instance-types":"c6in.2xlarge, c6in.xlarge"}
{"level":"INFO","time":"2024-01-24T15:43:21.197Z","logger":"controller.provisioner","message":"created nodeclaim","commit":"2dd7fdc","nodepool":"memcached-spot","nodeclaim":"memcached-spot-69l9r","requests":{"cpu":"2155m","memory":"4216Mi","pods":"6"},"instance-types":"c6in.2xlarge, c6in.xlarge"}
{"level":"ERROR","time":"2024-01-24T15:43:22.130Z","logger":"controller.nodeclaim.lifecycle","message":"creating instance, insufficient capacity, with fleet error(s), UnfulfillableCapacity: Unable to fulfill capacity due to your request configuration. Please adjust your request and try again.","commit":"2dd7fdc","nodeclaim":"memcached-spot-69l9r"}
{"level":"INFO","time":"2024-01-24T15:43:22.159Z","logger":"controller.nodeclaim.termination","message":"deleted nodeclaim","commit":"2dd7fdc","nodeclaim":"memcached-spot-69l9r","node":"","provider-id":""}
{"level":"INFO","time":"2024-01-24T15:43:23.374Z","logger":"controller.nodeclaim.lifecycle","message":"launched nodeclaim","commit":"2dd7fdc","nodeclaim":"memcached-sdk7g","provider-id":"aws:///us-east-1a/i-0e26a8106c65b60d1","instance-type":"c6in.xlarge","zone":"us-east-1a","capacity-type":"on-demand","allocatable":{"cpu":"3920m","ephemeral-storage":"17Gi","memory":"6584Mi","pods":"58","vpc.amazonaws.com/pod-eni":"18"}}
{"level":"INFO","time":"2024-01-24T15:43:23.429Z","logger":"controller.nodeclaim.lifecycle","message":"launched nodeclaim","commit":"2dd7fdc","nodeclaim":"memcached-hxtbj","provider-id":"aws:///us-east-1c/i-0f8b8d7aae0c75554","instance-type":"c6in.xlarge","zone":"us-east-1c","capacity-type":"on-demand","allocatable":{"cpu":"3920m","ephemeral-storage":"17Gi","memory":"6584Mi","pods":"58","vpc.amazonaws.com/pod-eni":"18"}}
{"level":"INFO","time":"2024-01-24T15:43:31.091Z","logger":"controller.provisioner","message":"found provisionable pod(s)","commit":"2dd7fdc","pods":"default/memcached-0, default/memcached-2, default/memcached-1","duration":"24.778447ms"}
{"level":"INFO","time":"2024-01-24T15:43:31.091Z","logger":"controller.provisioner","message":"computed new nodeclaim(s) to fit pod(s)","commit":"2dd7fdc","nodeclaims":2,"pods":2}
{"level":"INFO","time":"2024-01-24T15:43:31.091Z","logger":"controller.provisioner","message":"computed 1 unready node(s) will fit 1 pod(s)","commit":"2dd7fdc"}
{"level":"INFO","time":"2024-01-24T15:43:31.106Z","logger":"controller.provisioner","message":"created nodeclaim","commit":"2dd7fdc","nodepool":"memcached","nodeclaim":"memcached-dpc4h","requests":{"cpu":"2155m","memory":"4216Mi","pods":"6"},"instance-types":"c6in.2xlarge, c6in.xlarge"}
{"level":"INFO","time":"2024-01-24T15:43:31.109Z","logger":"controller.provisioner","message":"created nodeclaim","commit":"2dd7fdc","nodepool":"memcached","nodeclaim":"memcached-657sw","requests":{"cpu":"2155m","memory":"4216Mi","pods":"6"},"instance-types":"c6in.2xlarge, c6in.xlarge"}
{"level":"INFO","time":"2024-01-24T15:43:32.990Z","logger":"controller.nodeclaim.lifecycle","message":"launched nodeclaim","commit":"2dd7fdc","nodeclaim":"memcached-657sw","provider-id":"aws:///us-east-1b/i-0b8eebec642c46da8","instance-type":"c6in.xlarge","zone":"us-east-1b","capacity-type":"on-demand","allocatable":{"cpu":"3920m","ephemeral-storage":"17Gi","memory":"6584Mi","pods":"58","vpc.amazonaws.com/pod-eni":"18"}}
{"level":"INFO","time":"2024-01-24T15:43:32.991Z","logger":"controller.nodeclaim.lifecycle","message":"launched nodeclaim","commit":"2dd7fdc","nodeclaim":"memcached-dpc4h","provider-id":"aws:///us-east-1c/i-0716c42efa888c9a8","instance-type":"c6in.xlarge","zone":"us-east-1c","capacity-type":"on-demand","allocatable":{"cpu":"3920m","ephemeral-storage":"17Gi","memory":"6584Mi","pods":"58","vpc.amazonaws.com/pod-eni":"18"}}
{"level":"INFO","time":"2024-01-24T15:43:51.089Z","logger":"controller.provisioner","message":"found provisionable pod(s)","commit":"2dd7fdc","pods":"default/memcached-0, default/memcached-2, default/memcached-1","duration":"17.510219ms"}
{"level":"INFO","time":"2024-01-24T15:43:51.089Z","logger":"controller.provisioner","message":"computed new nodeclaim(s) to fit pod(s)","commit":"2dd7fdc","nodeclaims":1,"pods":1}
{"level":"INFO","time":"2024-01-24T15:43:51.089Z","logger":"controller.provisioner","message":"computed 2 unready node(s) will fit 2 pod(s)","commit":"2dd7fdc"}
{"level":"INFO","time":"2024-01-24T15:43:51.111Z","logger":"controller.provisioner","message":"created nodeclaim","commit":"2dd7fdc","nodepool":"memcached-spot","nodeclaim":"memcached-spot-hfgcn","requests":{"cpu":"2155m","memory":"4216Mi","pods":"6"},"instance-types":"c6in.2xlarge, c6in.xlarge"}
{"level":"INFO","time":"2024-01-24T15:43:53.213Z","logger":"controller.nodeclaim.lifecycle","message":"launched nodeclaim","commit":"2dd7fdc","nodeclaim":"memcached-spot-hfgcn","provider-id":"aws:///us-east-1a/i-027c0090f92c58ae3","instance-type":"c6in.xlarge","zone":"us-east-1a","capacity-type":"spot","allocatable":{"cpu":"3920m","ephemeral-storage":"17Gi","memory":"6584Mi","pods":"58","vpc.amazonaws.com/pod-eni":"18"}}
{"level":"INFO","time":"2024-01-24T15:43:59.111Z","logger":"controller.nodeclaim.lifecycle","message":"initialized nodeclaim","commit":"2dd7fdc","nodeclaim":"memcached-hxtbj","provider-id":"aws:///us-east-1c/i-0f8b8d7aae0c75554","node":"ip-10-0-171-164.ec2.internal"}
{"level":"INFO","time":"2024-01-24T15:44:01.012Z","logger":"controller.nodeclaim.lifecycle","message":"initialized nodeclaim","commit":"2dd7fdc","nodeclaim":"memcached-sdk7g","provider-id":"aws:///us-east-1a/i-0e26a8106c65b60d1","node":"ip-10-0-57-20.ec2.internal"}
{"level":"INFO","time":"2024-01-24T15:44:07.201Z","logger":"controller.nodeclaim.lifecycle","message":"initialized nodeclaim","commit":"2dd7fdc","nodeclaim":"memcached-dpc4h","provider-id":"aws:///us-east-1c/i-0716c42efa888c9a8","node":"ip-10-0-161-76.ec2.internal"}
{"level":"INFO","time":"2024-01-24T15:44:08.526Z","logger":"controller.nodeclaim.lifecycle","message":"initialized nodeclaim","commit":"2dd7fdc","nodeclaim":"memcached-657sw","provider-id":"aws:///us-east-1b/i-0b8eebec642c46da8","node":"ip-10-0-112-48.ec2.internal"}
{"level":"INFO","time":"2024-01-24T15:44:28.164Z","logger":"controller.nodeclaim.lifecycle","message":"initialized nodeclaim","commit":"2dd7fdc","nodeclaim":"memcached-spot-hfgcn","provider-id":"aws:///us-east-1a/i-027c0090f92c58ae3","node":"ip-10-0-46-176.ec2.internal"}
{"level":"INFO","time":"2024-01-24T15:44:49.551Z","logger":"controller.disruption","message":"disrupting via emptiness delete, terminating 1 candidates ip-10-0-161-76.ec2.internal/c6in.xlarge/on-demand","commit":"2dd7fdc"}
{"level":"INFO","time":"2024-01-24T15:44:50.202Z","logger":"controller.node.termination","message":"tainted node","commit":"2dd7fdc","node":"ip-10-0-161-76.ec2.internal"}
{"level":"INFO","time":"2024-01-24T15:44:50.681Z","logger":"controller.node.termination","message":"deleted node","commit":"2dd7fdc","node":"ip-10-0-161-76.ec2.internal"}
{"level":"INFO","time":"2024-01-24T15:44:51.104Z","logger":"controller.nodeclaim.termination","message":"deleted nodeclaim","commit":"2dd7fdc","nodeclaim":"memcached-dpc4h","node":"ip-10-0-161-76.ec2.internal","provider-id":"aws:///us-east-1c/i-0716c42efa888c9a8"}
{"level":"INFO","time":"2024-01-24T15:45:04.712Z","logger":"controller.disruption","message":"disrupting via emptiness delete, terminating 1 candidates ip-10-0-46-176.ec2.internal/c6in.xlarge/spot","commit":"2dd7fdc"}
{"level":"INFO","time":"2024-01-24T15:45:05.232Z","logger":"controller.node.termination","message":"tainted node","commit":"2dd7fdc","node":"ip-10-0-46-176.ec2.internal"}
{"level":"INFO","time":"2024-01-24T15:45:05.688Z","logger":"controller.node.termination","message":"deleted node","commit":"2dd7fdc","node":"ip-10-0-46-176.ec2.internal"}
{"level":"INFO","time":"2024-01-24T15:45:06.099Z","logger":"controller.nodeclaim.termination","message":"deleted nodeclaim","commit":"2dd7fdc","nodeclaim":"memcached-spot-hfgcn","node":"ip-10-0-46-176.ec2.internal","provider-id":"aws:///us-east-1a/i-027c0090f92c58ae3"}
```

**Comment by jmdeal** [comment] 2024-01-29 17:34
I'll have a detailed update later today or tomorrow, I believe I've been able to root cause the issue and am working on confirming. I believe this is caused by persistent volume topology requirements not being compatible with the initial set of NodeClaims Karpenter creates. This causes Karpenter to launch one or more NodeClaims to correct for the topology incompatibilities but Karpenter isn't aware of the domains of in-flight NodeClaims. Discussed offline but a potential workaround would be to set `minDomains` on your `topologySpreadConstraints`. This ensures that the scheduler is aware of the number of domains Karpenter can create and would prevent this scenario. Until the underlying bug is fixed this would result in some amount of node churn and is not ideal but is a temporary path towards correctness.

**Comment by jmdeal** [comment] 2024-03-08 18:23
Sorry this has taken a while to get an effective RCA, I believe I've been able to track it down. I was somewhat right that this is caused by the Persistent Volumes, but I wasn't totally correct. I'll try my best to explain. 

Before Karpenter considers pods for scheduling, it first injects discovered volume topology requirements. This is to ensure that Karpenter provisions nodes in the same AZ as their persistent volumes. This is modeled by adding a zonal requirement to each of the pods' node affinity terms (in-memory). This works well until we start to consider topologySpreadConstraints. Since only pods on nodes that match a given pod's node affinity are counted when computing the topology spread by default, by injecting this zonal node affinity requirement, we essentially create a separate topology spread group per zone, where only pods with volumes in the same zone count against each others' topology spread constraints. 

Definitely still need to do some more validation and testing, once I do we can open a new issue to track in the [upstream repo](https://github.com/kubernetes-sigs/karpenter) since this is likely bug in the core scheduling code. The other thing I have to validate first is that this is not expected behavior from the kube-scheduler side of things. It definitely doesn't seem like it should be but if the kube-scheduler also considers topology spread constraints as node affinities internally and applies them to topologySpeadConstraints our modeling might be accurate. Like I said, I don't think that's the case but I'll need to verify before attempting a fix from the Karpenter end.

**Comment by omri-kaslasi** [comment] 2024-04-07 14:05
Any ETA on this issue?
@jmdeal

**Comment by jmdeal** [comment] 2024-05-07 06:05
I'm going to close out this issue in favor of the linked upstream issue, I don't have any ETA to share atm, but I am confident in the RCA and will hopefully have some bandwidth to work on closing this out soon.

**Closed by jmdeal** 2024-05-07 06:05 UTC
Labels: bug
