### ISSUE TITLE
Reinstate support for referencing unmanaged AWS Launch Templates in v1beta1

### ISSUE THREAD

**Issue by jellyfish-headphones** [aws/karpenter-provider-aws#5918] opened 2024-03-22 17:50 UTC
### Description

**What problem are you trying to solve?**
Our infrastructure relies on launch templates which contain very long userdata scripts. These launch templates are managed and deployed by Terraform. With Karpenter upgrading to v1beta1, the ability to reference a launch template, i.e., with `spec.launchTemplateName` or `spec.provider.launchTemplate` has been removed. I know there has been some discussion about potentially reinstating this feature if enough people request it, so this is my way of adding my voice to the chorus.

**How important is this feature to you?**
Very important. The ability to provision nodes according to launch templates is crucial to our operations. As it stands, there is no clean solution or reasonably manageable way for us to work around this issue.

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by engedaam** [comment] 2024-03-25 05:01
Closing as a duplicate of https://github.com/aws/karpenter-provider-aws/issues/3369

**Closed by engedaam** 2024-03-25 05:02 UTC
Labels: feature, needs-triage
