### ISSUE TITLE
Optimizing Karpenter Provisioning for GPU-Based EKS Node Groups

### ISSUE THREAD

**Issue by dhanushgowda91** [aws/karpenter-provider-aws#6330] opened 2024-06-06 23:00 UTC
### Description

Hi Team,

Need some help
We have Karpenter set up for GPU-based EKS node groups in our cluster. When a user opens a learning lab, it triggers the creation of a pod in our cluster. We've implemented time slicing to use virtual GPUs, but we're encountering issues when multiple concurrent requests occur.

Currently, Karpenter spins up multiple nodes to accommodate the incoming requests. However, it only detects the presence of virtual GPUs after the nodes have been provisioned. As a result, Karpenter then evicts pods to nodes with virtual GPUs and terminates the additional nodes. This eviction process negatively impacts user labs, causing disruption. Any solution will be greatly appreciated

**Comment by tzneal** [comment] 2024-06-07 13:44
Closing as a duplicate of https://github.com/kubernetes-sigs/karpenter/issues/729 / https://github.com/kubernetes-sigs/karpenter/issues/751 .  

In the interim you may be able to use the [pod level controls](https://karpenter.sh/docs/concepts/disruption/#pod-level-controls) to prevent pods from getting evicted, which could help. Though it would prevent consolidation of nodes with those pods which may lead to increased cost.

**Closed by tzneal** 2024-06-07 13:44 UTC
Labels: feature, needs-triage

**Comment by glikson** [comment] 2025-05-08 07:13
@dhanushgowda91 have you considered using 'preferred' pod affinity between jobs, to avoid them from getting scheduled on different nodes in the first place?
