### ISSUE TITLE
Pods allocation on a WorkerNode reservation

### ISSUE THREAD

**Issue by arseny-zinchenko** [aws/karpenter-provider-aws#5526] opened 2024-01-25 11:29 UTC
### Description

**What problem are you trying to solve?**

Will be nice to have a way to reserve some Pods allocation on the WorkerNodes: currently, having `consolidationPolicy: WhenUnderutilized` makes Karpenter to pur Pods on Nodes around 100% of a Node Pods Allocation capacity.
Then, when a new Pod(s) are created, they have to wait while Kaprnter will spin up a new Nodes.

**How important is this feature to you?**

It's close to a critical feature, as affects the overall cluster's stability.

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by ellistarn** [comment] 2024-01-26 22:04
Closing as duplicate of https://github.com/kubernetes-sigs/karpenter/issues/749

**Closed by ellistarn** 2024-01-26 22:04 UTC
Labels: feature, needs-triage
