### ISSUE TITLE
Karpenter 1.0.x Helm Chart Update

### ISSUE THREAD

**Issue by mhamzarazzaq97** [aws/karpenter-provider-aws#6873] opened 2024-08-26 11:03 UTC
### Description

**What problem are you trying to solve?**
I am trying upgrade to karpenter 1.0.x, but in the latest release (1.0.1) in this repository,  it is using older helm chart i.e. 0.37.x. Changes are present in main branch but not in the latest release.

**How important is this feature to you?** 
It is essential to upgrade to karpenter 1.0.x version.

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jmdeal** [comment] 2024-08-26 17:02
Closing as a duplicate of https://github.com/aws/karpenter-provider-aws/issues/5415.

**Closed by jmdeal** 2024-08-26 17:02 UTC
Labels: feature, needs-triage
