### ISSUE TITLE
Allocation strategies for Spot Instances

### ISSUE THREAD

**Issue by lzyli** [aws/karpenter-provider-aws#7088] opened 2024-09-27 04:49 UTC
### Description

**What problem are you trying to solve?**
Spot fleet supports multiple strategies to optimize cost or availability. I would like to set a strategy to provide a spot instance.
**How important is this feature to you?**
Highly important, It helps us increase HA and cost optimization also.
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jmdeal** [comment] 2024-10-04 22:24
Going to close as a duplicate of #1240. If you have any additional details on why you want to select a strategy other than `PriceCapacityOptimized`, please add them there.

**Closed by jmdeal** 2024-10-04 22:24 UTC
Labels: feature, needs-triage
