### ISSUE TITLE
DaemonSets shutdown before waiting for deployments to gracefully shutdown 

### ISSUE THREAD

**Issue by nikskiz** [aws/karpenter-provider-aws#5858] opened 2024-03-14 01:15 UTC
### Description

**Observed Behavior**:

I noticed that `kind: Daemonset` pods are being shut down before `kind: deployment` pods. We have set `priorityClassName: system-node-critical` on the daemonset.

This can be observed by watching all the pod on a node. And, we have observed some daemonset pods shut down simultaneously as deployment pods.
```
watch -n 0.1 kubectl get pods --all-namespaces --field-selector spec.nodeName=<NODE>
```

Putting a `preStop` on the daemon set is not obeyed. 

 `aws-node` and `kube-proxy` daemonsets seem to remain active during the shutdown of the deployment pods.

To reproduce the bug we have performed the following:
1. Set a preStop of 130 seconds on deployment pods. This is to slow down the shutdown of deployment pods. Makes observation easier. 
2. Start watching all the pods on the node
```
watch -n 0.1 kubectl get pods --all-namespaces --field-selector spec.nodeName=<NODE>
``` 
3. Delete the node
```
kubectl delete node <NODE>
```
Note: The command `kubectl delete node <NODE>` mimics the issue of when karpenter decides to shutdown a node. An Alternative is not to use `kubectl delete node <NODE>` and cordon all nodes, then restart a deployment to force a new node to be scheduled. When the new node is scheduled, you can uncordon all the nodes so that karpenter decides to shut down a node.

3. Obersve the daemonset pods, and notice that they will shut down before the deployment pods. 

**Expected Behavior**:

Daemonset pods to be terminated gracefully, and wait for deployment pods to terminate gracefully.

**Versions**:
- Chart Version: 0.35.1 (karpenter on fargate)
- Kubernetes Version (`kubectl version`): 1.29.0

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jonathan-innis** [comment] 2024-03-15 01:28
So, seems like this has been the behavior since we have been doing pod ordering, so I wouldn't necessarily classify this as a bug. We should talk about this more, though. I do think that it makes sense to wait until the pod is fully gone so that you still get logs from your pods while they may be executing a pre-stop. 

What's the use-case that you are using a pre-stop and you need your DaemonSet pods to keep running?

**Comment by njtran** [comment] 2024-03-15 16:51
I actually think this is a bit different. 

Going back to a previous version ([v0.33.1](https://github.com/kubernetes-sigs/karpenter/blob/v0.33.1/pkg/controllers/node/termination/terminator/terminator.go#L87-L102)), our drain logic would pull all pods we wanted to evict, group them by class (non-critical non-daemon, non-critical daemon, critical non-daemon, critical daemon), and evict the next group when the previous group is completely empty.

I'm noticing that our logic now filters out pods that are terminating in this check, which means we're continuing to the next class of pods before the previous group is fully cleaned up. 

I do think this was an unexpected change in behavior from #789, and judging by the quick nature of the termination controller: if there are no blocking PDBs, this grouping is redundant as we'd just enqueue the four groups of pods in quick succession. 

@nikskiz Judging by your reproduction steps, you're able to see critical and non-critical pods deleting at the same time, which I would imagine one group would wait for the other.

**Comment by jonathan-innis** [comment] 2024-03-17 02:35
> now filters out pods that are terminating in this check, which means we're continuing to the next class of pods before the previous group is fully cleaned up

@njtran and I discussed offline, the behavior didn't change prior to v0.33.1 due to https://github.com/kubernetes-sigs/karpenter/blob/v0.33.0/pkg/controllers/node/termination/terminator/terminator.go#L115. This line has been in there for a really long time so this is effectively the behavior that Karpenter has always had.

Whether this should be the behavior is a different question. I'm personally aligned that we _should_ wait (as you are saying @nikskiz) for each group to be fully deleted before we move on evicting the next one.

**Comment by awilmore** [comment] 2024-03-18 00:05
Just wanted to add something I thought might help put some weight behind this issue.

An example of where this behaviour is an issue for us is with pods that send metrics to our otel agents. On node deletion, the otel agent (with `priorityClassName: system-node-critical` applied) is removed before other pods get a chance to post their final metric payload, causing the pods to terminate with errors. This also results in a small about of data loss in the form of uncollected logs and metrics.

This has become a blocker for us as we look to replace the EKS cluster autoscaler with Karpenter.

**Comment by nikskiz** [comment] 2024-03-19 00:06
@awilmore has clarified our use case. 

@jonathan-innis I agree that we wait for each group to complete shutdown, before moving onto the next. 

Also, to add onto the reason why we have a presStop configured (which makes our pod shutdown slower)
A) Pod assigned directly to an ALB/NLB, where we have to wait for the ALB/NLB to stop accepting new connections.
B) We run sidecar proxy in each pod, so we need to ensure the sidecar proxy is terminated first.

In our current node shutdown process with cluster-autoscaler, the controller will shutdown the daemonsets at the end.

We are curious to know why we don't see `kube-prxoxy` and `aws-node` (kubelet) shutdown at the same time as other daemonsets?

**Comment by njtran** [comment] 2024-03-21 16:39
What are the tolerations on your other daemonsets? the `kube-proxy` and `aws-node` daemonsets tolerate all taints, so they're not cleaned up the same way others are: https://github.com/kubernetes-sigs/karpenter/issues/621

**Comment by aquam8** [comment] 2024-03-21 22:16
That is interesting @njtran , thank you for pointing this out.
Our `kube-proxy` daemonset has this tolerations:
```
      tolerations:
      - operator: Exists
 ```
which means that it will tolerate everything as per ["An empty key with operator Exists matches all keys, values and effects which means this will tolerate everything"](https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/#concepts)

The other suggestion to add the [graceful shutdown](https://kubernetes.io/blog/2021/04/21/graceful-node-shutdown-beta/#how-do-i-use-it) is worth exploring again first tho.

Thank you for your contribution

**Comment by njtran** [comment] 2024-04-05 00:15
Since this an issue regardless of the cloud provider I'll close this one in favor of the linked upstream issue at github.com/kubernetes-sigs/karpenter/issues/1133

**Closed by njtran** 2024-04-05 00:15 UTC
Labels: feature
