### ISSUE TITLE
Migrate one application at a time rather than entire cluster

### ISSUE THREAD

**Issue by manojmspython** [aws/karpenter-provider-aws#5243] opened 2023-12-05 22:55 UTC
My cluster has bunch of applications which are already using bunch of autoscalers . Can karpenter be used to manage one of these applications rather than migrating the entire cluster

**Comment by jonathan-innis** [comment] 2023-12-07 08:39
> Can karpenter be used to manage one of these applications rather than migrating the entire cluster

Hoping to get a more fleshed-out answer to this question through this issue: #5187.

Realistically, the answer to this question is to taint the NodePool that you are creating with Karpenter. This will ensure that other pods won't schedule against the NodePool because they won't tolerate the taint. You can then add the tolerations to your application for that taint so that Karpenter will start scheduling capacity against those pods. The other key thing here is that you need to make sure that those applications will always schedule against Karpenter-managed capacity (if that's what you want) and not against other autoscalers. You can use `nodeSelector`/`nodeAffinity` combined with the taint-based approach to achieve this.

**Comment by manojmspython** [comment] 2023-12-07 23:07
@jonathan-innis  Thanks for answering this. Looking forward for the documenation

**Comment by njtran** [comment] 2023-12-11 22:14
Closing as dupe of #5187

**Closed by njtran** 2023-12-11 22:14 UTC
Labels: question
