### ISSUE TITLE
[Feature Request] Limit the time Karpenter keeps the nodes that aren't initialized

### ISSUE THREAD

**Issue by chiragjn** [aws/karpenter-provider-aws#6124] opened 2024-05-01 16:14 UTC
> Is there a way to limit the time Karpenter keeps the nodes that aren't initialized? 
And add logs for visibility to understand why these nodes aren't removed?

> In my case, because of my miss configuration the nodes were up for over 24 hours, this configuration issue can be pretty costly if Karpenter keeps these nodes forever 😅 

> Thanks!

_Originally posted by @itaibenyishai in https://github.com/aws/karpenter-provider-aws/issues/1914#issuecomment-1153098521_
            
We ran into a similar issue where we blew the bill on a large gpu node where device plugin got stuck for multiple days for whatever reason.

While I understand the reasoning to not remove to be able to debug the root cause, but a choice on how long would be nice?

**Comment by engedaam** [comment] 2024-05-01 20:04
Closing this as a duplicate of https://github.com/kubernetes-sigs/karpenter/issues/750

**Closed by engedaam** 2024-05-01 20:04 UTC
