### ISSUE TITLE
"webhook","message":"http: TLS handshake error from 10.53.153.172:44064: read tcp 10.53.230.139:8443->10.53.153.172:44064: read: connection reset by peer\n","commit":"0ebc224"}

### ISSUE THREAD

**Issue by avmehta768** [aws/karpenter-provider-aws#7189] opened 2024-10-09 12:34 UTC
### Description

Hi Team,

WE have installed karpenterv0.37.4 , but getting the same error in karpenter pods, however nodes are getting provisioned/deprovisioned, so no issue in functionality. 

[root@ip-10-53-57-140 ~]# k logs -f karpenter-7cd544f894-s8b8m -n karpenter --tail=100
{"level":"INFO","time":"2024-10-09T07:27:20.769Z","logger":"controller.controller-runtime.metrics","message":"Starting metrics server","commit":"0ebc224"}
{"level":"INFO","time":"2024-10-09T07:27:20.770Z","logger":"controller.controller-runtime.metrics","message":"Serving metrics server","commit":"0ebc224","bindAddress":":8000","secure":false}
{"level":"INFO","time":"2024-10-09T07:27:20.770Z","logger":"controller","message":"starting server","commit":"0ebc224","name":"health probe","addr":"[::]:8081"}
{"level":"INFO","time":"2024-10-09T07:27:20.873Z","logger":"controller","message":"attempting to acquire leader lease karpenter/karpenter-leader-election...","commit":"0ebc224"}
{"level":"ERROR","time":"2024-10-09T08:50:17.156Z","logger":"webhook","message":"http: TLS handshake error from 10.53.153.172:60594: EOF\n","commit":"0ebc224"}
{"level":"ERROR","time":"2024-10-09T09:01:46.919Z","logger":"webhook","message":"http: TLS handshake error from 10.53.153.172:56710: EOF\n","commit":"0ebc224"}
{"level":"ERROR","time":"2024-10-09T09:02:18.043Z","logger":"webhook","message":"http: TLS handshake error from 10.53.153.172:59026: read tcp 10.53.230.139:8443->10.53.153.172:59026: read: connection reset by peer\n","commit":"0ebc224"}
{"level":"ERROR","time":"2024-10-09T09:40:18.045Z","logger":"webhook","message":"http: TLS handshake error from 10.53.153.172:44064: read tcp 10.53.230.139:8443->10.53.153.172:44064: read: connection reset by peer\n","commit":"0ebc224"}
{"level":"ERROR","time":"2024-10-09T10:22:55.021Z","logger":"webhook","message":"http: TLS handshake error from 10.53.96.182:54718: EOF\n","commit":"0ebc224"}
{"level":"ERROR","time":"2024-10-09T11:29:10.097Z","logger":"webhook","message":"http: TLS handshake error from 10.53.153.172:44720: EOF\n","commit":"0ebc224"}
{"level":"ERROR","time":"2024-10-09T11:33:50.286Z","logger":"webhook","message":"http: TLS handshake error from 10.53.96.182:51540: EOF\n","commit":"0ebc224"}

**Expected Behavior**: Karpenter should work without any errors/issues.

**Reproduction Steps** (Please include YAML): [attached]

**Versions**:
- Chart Version:
-NAME            NAMESPACE       REVISION        UPDATED                                 STATUS          CHART                   APP VERSION
karpenter       karpenter       4               2024-10-09 07:20:05.904019626 +0000 UTC deployed        karpenter-0.37.4        0.37.4
karpenter-crd   karpenter       1               2024-10-04 04:51:35.501653904 +0000 UTC deployed        karpenter-crd-0.37.4    
- Kubernetes Version (`kubectl version`):1.30

Let me know in case any other details required on this issue.

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by avmehta768** [comment] 2024-10-09 12:43
Also, Tried running the below command and getting this if this will be helpful in checking the issue.
kubectl get MutatingWebhookConfiguration defaulting.webhook.karpenter.k8s.aws -o jsonpath='{.webhooks[].clientConfig.caBundle}' | base64 -d > webhook-ca-cert.pem
kubectl get secret -n karpenter karpenter-cert -o jsonpath='{.data.server-cert\.pem}' | base64 -d > server-cert.pem
[root@ip-10-53-57-140 ~]# openssl verify -verbose -CAfile webhook-ca-cert.pem server-cert.pem
O = knative.dev, CN = karpenter.karpenter.svc
error 18 at 0 depth lookup: self-signed certificate
error server-cert.pem: verification failed

but doubt is if both the certs are created by karpenter itself, then why its showing validation failed, Kindly check and support.

**Comment by bernermic** [comment] 2024-10-10 07:13
Hello,

I am facing the same issue and this are my versions in use:

Karpenter CRD Helm chart `v0.37.4` 
Karpenter Helm chart `v0.37.4`
Kubernetes version in use: `v1.31.0-eks-a737599`

In the meantime I upgraded karpenter to `v1.0.6` and can still see the issue.

Nodes scaling with karpenter is working, but log shows this errors.

 Greetings

**Comment by jmdeal** [comment] 2024-10-10 17:01
Closing as a duplicate of https://github.com/aws/karpenter-provider-aws/issues/6898.

**Closed by jmdeal** 2024-10-10 17:01 UTC
Labels: bug, needs-triage
