### ISSUE TITLE
Update grafana dashboards for v0.33

### ISSUE THREAD

**Issue by Hronom** [aws/karpenter-provider-aws#5533] opened 2024-01-26 01:29 UTC
### Description

**Observed Behavior**:
Dashboards still use `provisioner` however metrics right now rely on `nodepool`.
In v0.33 old alpha api was deprecated.

**Expected Behavior**:
Align grafana dashboards with breaking changes in v0.33

**Reproduction Steps** (Please include YAML):

**Versions**:
- Chart Version: v0.33.1
- Kubernetes Version (`kubectl version`): v1.28.4-eks-8cb36c9

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jonathan-innis** [comment] 2024-01-26 06:17
This looks like a duplicate of #4838. @Hronom Is this something that you would be willing to help us get updated? The maintainers don't currently have bandwidth to work on this unfortunately?

**Closed by jonathan-innis** 2024-01-26 06:17 UTC
Labels: documentation

**Comment by Hronom** [comment] 2024-01-27 18:09
@jonathan-innis created https://github.com/aws/karpenter-provider-aws/pull/5546 please help to push
