### ISSUE TITLE
Metric karpenter_interruption_received_messages(message_type="SpotInterruptionKind") is not accurate

### ISSUE THREAD

**Issue by hitsub2** [aws/karpenter-provider-aws#6531] opened 2024-07-17 13:57 UTC
### Description

**Observed Behavior**:
Currently Karpenter recieves the account all the spot interruption and filters in the karpenter controller logic. But we have setup a lambda to filter the interruption message and sends to the related sqs. So karpenter only receieves the spot interruption belongs to it.

When taking care of the spot interruption, Karpenter emits the metric karpenter_interruption_received_messages(message_type="SpotInterruptionKind") + 2 for every single spot interruption. For example, if there is one spot interruption, this metric value is 2.

**Expected Behavior**:

karpenter_interruption_received_messages(message_type="SpotInterruptionKind") = how many spot instance is interrupted

**Reproduction Steps** (Please include YAML):

**Versions**:
- Chart Version: 0.37.0
- Kubernetes Version (`kubectl version`): 1.29

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jigisha620** [comment] 2024-07-26 17:55
I have been trying to reproduce the issue but I haven't seen this behavior occur even once in my testing. Do you have karpenter controller logs from when this happened? Specifically looking for log with message `initiating delete from interruption message`.

**Comment by hitsub2** [comment] 2024-07-28 02:34
[karpenter (4).log](https://github.com/user-attachments/files/16402038/karpenter.4.log)

It is very easy to reproduce this issue. I just tested it with FIS, the metric is always + 2 for every single spot interruption.

**Comment by jigisha620** [comment] 2024-08-12 18:51
I spent more time trying to reproduce this issue using FIS, just like you mentioned. Every time I only got one event. 
These are metrics from prometheus

<img width="680" alt="Screenshot 2024-08-12 at 11 49 22 AM" src="https://github.com/user-attachments/assets/be7bf0fe-538e-4024-9cc6-ec028117b677">

And here's the grafana dashboard

<img width="1063" alt="Screenshot 2024-08-12 at 11 49 46 AM" src="https://github.com/user-attachments/assets/67bf5bf0-1e08-4ed5-b746-3adf79738833">

**Comment by hitsub2** [comment] 2024-10-10 02:09
@jigisha620  May I know your Karpenter version?

**Comment by jigisha620** [comment] 2024-10-12 20:56
I have tried reproducing this on 0.37.0.

**Comment by hitsub2** [comment] 2024-10-13 14:32
We have a cluster with Karpenter 0.36.0, this metric got two events for every single spot interruption.

**Comment by hitsub2** [comment] 2024-10-13 15:25
After testing the version of 0.37.5, this metric got only one event for every single spot interruption. So this is fixed between 0.36.0-0.37.5, but we do not find any info on releases notes. Could you help confirm which version fix this issue?

**Comment by jonathan-innis** [comment] 2024-12-13 17:55
Closing this since this looks to be solved.

**Closed by jonathan-innis** 2024-12-13 17:55 UTC
Labels: bug, needs-triage
