### ISSUE TITLE
Add script to run after bootstrap in userdata

### ISSUE THREAD

**Issue by wkd3475** [aws/karpenter-provider-aws#5738] opened 2024-02-27 08:15 UTC
### Description

**What problem are you trying to solve?**
Sometimes I need to perform a specific action after executing bootstrap.sh.
But now we can only put custom userdata before running bootstrap.sh.
It would be nice to have a setting like customAfterUserData.

**How important is this feature to you?**
After bootstrap.sh is executed, I need to run "systemctl restart runtime.slice".

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by njtran** [comment] 2024-03-11 17:20
What are you trying to run after the boostrap.sh script? What can't be handled through adding it at the end of your userData?

**Comment by jonathan-innis** [comment] 2024-03-11 22:22
This looks like a duplicate of #3915. Do you mind adding a +1 to that issue and than any additional context that you want to share for your use-case?

**Comment by jonathan-innis** [comment] 2024-03-11 22:22
Closing as a duplicate.

**Closed by jonathan-innis** 2024-03-11 22:22 UTC
Labels: feature, needs-triage
