### ISSUE TITLE
Chart version is not semantic and facing issue in installation with kubeapps

### ISSUE THREAD

**Issue by bala151187** [aws/karpenter-provider-aws#3689] opened 2023-04-03 14:29 UTC
### Version

__Karpenter Version:__ v0.27.1

__Kubernetes Version:__ v1.0.0

### Expected Behavior

https://github.com/vmware-tanzu/kubeapps/issues/6160

### Actual Behavior

https://github.com/vmware-tanzu/kubeapps/issues/6160

### Steps to Reproduce the Problem

https://github.com/vmware-tanzu/kubeapps/issues/6160

### Resource Specs and Logs

https://github.com/vmware-tanzu/kubeapps/issues/6160

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by absoludity** [comment] 2023-04-04 00:03
Just to add a bit more direct information from https://github.com/vmware-tanzu/kubeapps/issues/6160#issuecomment-1493432629 , the question here is why is a non-semantic version being used for karpenter's chart version when installing the chart? The Chart.yaml has the correct semantic version (ie. without the `v` prefix), but the images are tagged using a non-semantic version number (different to the Chart.yaml, with the `v` prefix).

As far as I can tell, all the helm and ECR docs use the same semantic version for the OCI image as has been used in the Chart.yaml (in fact, the `helm push` command would seem to force it this way), so it's unclear why this is not the case with the karpenter chart images?

Thanks for any info.

**Comment by ellistarn** [comment] 2023-05-09 00:11
Open minded to this, but we're focused elsewhere on critical bugs and performance improvements that have surfaced recently. Maybe we can explore this as part of v1?

**Comment by jonathan-innis** [comment] 2024-01-09 19:10
Realizing now that this looks to be a duplicate of #4248. I know this one has been open for longer, but I think the other issue has a bit more traction so closing this one in favor of that one.

**Closed by jonathan-innis** 2024-01-09 19:10 UTC
Labels: feature, v1
