### ISSUE TITLE
Documentation :  The documentation for version .34 doesn't carry over complete features from prior releases

### ISSUE THREAD

**Issue by agrawal1n** [aws/karpenter-provider-aws#5657] opened 2024-02-13 21:58 UTC
The documentation for version .34 doesn't carry over complete features from prior releases. This may make users assume that features covered in prior versions are not supported. This should be cumulative.

**Comment by jonathan-innis** [comment] 2024-02-13 22:18
> This may make users assume that features covered in prior versions are not supported

Can you be more specific about the features that aren't carried over from one version of the docs to the other that you think are missing?

**Comment by agrawal1n** [comment] 2024-02-13 22:54
If I compare with .31 documentation, most of the sections under Concepts are missing in 0.34

**Comment by jonathan-innis** [comment] 2024-02-13 23:44
> If I compare with .31 documentation

There was a major documentation re-work in v0.32.x where a bunch of stuff was remapped. We're constantly evolving our docs. If you are looking for an old page and old information, you should be able to find it by going to the older version of the docs, finding the page that you want, and then clicking the dropdown to move to the newer version of the docs. There should be redirects in place that should take you to the right place.

**Comment by agrawal1n** [comment] 2024-02-14 00:26
Thank you.  I see some sections are moved around but I don't see Provisioners in 0.34

**Comment by jmdeal** [comment] 2024-02-14 00:47
Provisioners no longer exist in v0.34. In v0.32 we introduced the new v1beta1 APIs and support for the alpha APIs was dropped in v0.33. You'll want to check out the [v0.32.0+ upgrade notes](https://karpenter.sh/docs/upgrading/upgrade-guide/#upgrading-to-v0320). NodePools are the v1beta1 equivalent of Provisioners.

**Comment by agrawal1n** [comment] 2024-02-14 00:49
Thank you for clarifying.On Feb 13, 2024, at 7:47 PM, Jason Deal ***@***.***> wrote:﻿
Provisioners no longer exist in v0.34. In v0.32 we introduced the new v1beta1 APIs and support for the alpha APIs was dropped in v0.33. You'll want to check out the v0.32.0+ upgrade notes. NodePools are the v1beta1 equivalent of Provisioners.

**Comment by jonathan-innis** [comment] 2024-02-14 05:18
Closing this one since it seems like there is nothing else for us to do here. This seems like the expected behavior from the documentation re-work that we did.

**Closed by jonathan-innis** 2024-02-14 05:18 UTC
Labels: question
