### ISSUE TITLE
Use dockerhub bitnami/kubectl for postInstallHook due to arm64 support

### ISSUE THREAD

**Issue by luong-komorebi** [aws/karpenter-provider-aws#6780] opened 2024-08-16 03:59 UTC
### Description

**What problem are you trying to solve?**

I have seen failures in my cluster when installing latest versions of karpenter or upgrading from the oldest version to the latest one. The error lies under a generic helm message of `timed out waiting for the condition` and when I debug more deeply, it turns out to be the postInstallHook's issue 

On amazon gallery for ecr, bitnami/kubectl does not support arm64. Therefore, on some set ups, this may either cause an issue upgrading that wastes everyone's time or lead to missed opportunity of using hardwares like amazon graviton 

**How important is this feature to you?**

Mildly important for the reasons listed above. While I can still modify the chart to use whatever image that I want, there are two things here that is quite counter-intuitive 

1. The digest is set by default in the values of the helm chart
2. The repo is set by default in the values of the helm chart

And I dont know if there are any rules of using amazon gallery's images only so I am not inclined to open a pull request for this 

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by stevehipwell** [comment] 2024-08-16 09:04
Why is a Bitnami image being used here? It's 293 MB compared to the official `kubectl` image (`registry.k8s.io/kubectl:v1.30.4`) which is 55 MB.

CC @njtran

**Comment by stevehipwell** [comment] 2024-08-16 09:27
@luong-komorebi that was meant for the maintainers. FYI this is a duplicate of #6775.

**Closed as completed** 2024-08-16 09:37 UTC
Labels: feature, needs-triage
